
const data = [
  {
    projectName: 'A logo is for company',
    clientName: 'oio raja',
    bidAmount: 120304,
    desc: 'this is good',
    duration: '2025-10-31',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 12003,
    email: 'oio@gmail.com',
    contact: '95620178965',
    location: 'canada',
    notes: 'this is good by the way for the event',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'low',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'Logo for denist pharam',
    clientName: 'jyoyi',
    bidAmount: 123030,
    desc: 'this is good',
    duration: '2025-11-09',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 120030,
    email: 'jyoti@gmail.com',
    contact: '95620147896',
    location: 'USA',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'medium',
    services: [],
    projectLogs: [],
  },
  {
    projectName: 'logo for a comany',
    clientName: 'Kunal pandit',
    bidAmount: null,
    desc: 'thi sis good',
    duration: '2025-11-01',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 2303,
    email: 'kunal@gmail.com',
    contact: '123456789',
    location: 'AMerica',
    notes: 'this is foof',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: 123030,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: [],
  },
  {
    projectName: 'logo redesign',
    clientName: 'harsh sharma',
    bidAmount: 12300,
    desc: 'this is better for my target',
    duration: '2025-11-01',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 12300,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 6,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'medium',
  }

  ,
  {
    projectName: 'Kio dataBase',
    clientName: 'kunal pandit',
    bidAmount: 1220,
    desc: 'this is good',
    duration: '2025-11-01',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 2330,
    email: 'kunal@gmail.com',
    contact: '9520611838',
    location: 'USA',
    notes: 'ffff',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'low',
  },
  {
    projectName: 'Website design for a company',
    clientName: 'Harsh sharma',
    bidAmount: 230040,
    desc: 'this is good',
    duration: '2025-11-09',
    userId: '68f8f93a6580ff27a86e8a85',
    userName: 'nikhil',
    clientBudget: 123588,
    email: 'harsh444577@gmail.com',
    contact: '9520611838',
    location: 'USA',
    notes: 'this is notes taken from the class',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: []
  },
  {
    projectName: 'completed SEO',
    clientName: 'Kunal sharma',
    bidAmount: null,
    desc: 'jfrr',
    duration: '2025-11-08',
    userId: '68f8f93a6580ff27a86e8a85',
    userName: 'nikhil',
    clientBudget: 12568.99,
    email: 'kunal@gmail.com',
    contact: '9520611838',
    location: 'dehradun',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: 1203,
    isNotified: false,
    projectPriority: 'low',
    services: [],
    projectLogs: []
  },
  {
    projectName: 'paper SEO for logo design',
    clientName: 'tushar shmara',
    bidAmount: 1200,
    desc: 'this i sgoof',
    duration: '2025-11-08',
    userId: '68f8f93a6580ff27a86e8a85',
    userName: 'nikhil',
    clientBudget: 1232.99,
    email: 'tushar@gmail.com',
    contact: '95020020',
    location: 'USA',
    notes: 'thi sis ',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: [],

    __v: 0
  }
  ,
  {
    projectName: 'A logo is for company',
    clientName: 'oio raja',
    bidAmount: 120304,
    desc: 'this is good',
    duration: '2025-10-31',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 12003,
    email: 'oio@gmail.com',
    contact: '95620178965',
    location: 'canada',
    notes: 'this is good by the way for the event',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'low',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'Logo for denist pharam',
    clientName: 'jyoyi',
    bidAmount: 123030,
    desc: 'this is good',
    duration: '2025-11-09',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 120030,
    email: 'jyoti@gmail.com',
    contact: '95620147896',
    location: 'USA',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'medium',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo for a comany',
    clientName: 'Kunal pandit',
    bidAmount: null,
    desc: 'thi sis good',
    duration: '2025-11-01',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 2303,
    email: 'kunal@gmail.com',
    contact: '123456789',
    location: 'AMerica',
    notes: 'this is foof',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: 123030,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo redesign',
    clientName: 'harsh sharma',
    bidAmount: 12300,
    desc: 'this is better for my target',
    duration: '2025-11-01',
    userId: '68f9a93dd6f345199272413c',
    userName: 'manvi joshi',
    clientBudget: 12300,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 6,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'medium',
    services: [[Object]],
    projectLogs: [[Object]],
    __v: 2
  }
  ,
  {
    projectName: 'Kio dataBase',
    clientName: 'kunal pandit',
    bidAmount: 1220,
    desc: 'this is good',
    duration: '2025-11-01',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 2330,
    email: 'kunal@gmail.com',
    contact: '9520611838',
    location: 'USA',
    notes: 'ffff',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'low',
    services: [[Object]],
    projectLogs: [[Object]],
    __v: 2
  },
  {
    projectName: 'logo redesign',
    clientName: 'Kunal',
    bidAmount: 22,
    desc: 'this is ',
    duration: '2025-11-01',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 2002,
    email: 'kio@gmail.com',
    contact: '1200202',
    location: 'usa',
    notes: 'this is goog',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 1,
    totalSec: 55,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'medium',
    services: [],
    projectLogs: [[Object]],
    __v: 1,
    tax_rate: '18'
  },
  {
    projectName: 'logo ',
    clientName: 'Kn',
    bidAmount: 12002,
    desc: 'fff',
    duration: '2025-10-26',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 120002,
    email: 'kn@gmail.com',
    contact: '1030330303',
    location: 'USA',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo redesign',
    clientName: 'harsh sharma',
    bidAmount: 8989,
    desc: 'jjk',
    duration: '2025-10-24',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 455555,
    email: 'kio@gmail.com',
    contact: '9783333333',
    location: 'ys',
    notes: 'kji',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: false,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: null,
    isNotified: false,
    projectPriority: 'low',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo redesign',
    clientName: 'harsh sharma',
    bidAmount: 122222,
    desc: 'fff',
    duration: '2025-11-09',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 12000,
    email: 'kio@gmail.com',
    contact: '9783333333',
    location: 'dehradun',
    notes: 'r',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: 1200,
    isNotified: false,
    projectPriority: 'high',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo redesign',
    clientName: 'harsh sharma',
    bidAmount: null,
    desc: 'fff',
    duration: '2025-10-18',
    userId: '68f9e03d822004b143d3790e',
    userName: 'Harsh coder',
    clientBudget: 4500,
    email: 'oip@gmail.com',
    contact: '978',
    location: 'dehradun',
    notes: 'ff',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 16,
    totalHour: 0,
    totalMin: 0,
    totalSec: 48,
    hourlyRate: 1200,
    isNotified: false,
    projectPriority: 'medium',
    services: [[Object]],
    projectLogs: [[Object], [Object]],
    __v: 3,
    tax_rate: '20'
  },
  {
    projectName: 'Website design for a company',
    clientName: 'harsh sharma',
    bidAmount: null,
    desc: 'this is a website for a company',
    duration: '2025-11-09',
    userId: '105838001901535106407',
    userName: 'Bonhive',
    clientBudget: 12000,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is my first project ',
    leadSource: 'others',
    proposal: '',
    status: 'completed',
    IshourBillable: true,
    totalBill: 1.9444444444444444,
    totalHour: 0,
    totalMin: 0,
    totalSec: 7,
    hourlyRate: 1000,
    isNotified: false,
    projectPriority: 'high',
    services: [[Object]],
    projectLogs: [[Object]],
    __v: 2,
    completedMonth: 'Oct'
  },
  {
    projectName: 'logo redesign for a company',
    clientName: 'harsh sharma',
    bidAmount: null,
    desc: 'this is good',
    duration: '2025-10-25',
    userId: '105838001901535106407',
    userName: 'Bonhive',
    clientBudget: 12000,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is better',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 0,
    totalHour: 0,
    totalMin: 0,
    totalSec: 0,
    hourlyRate: 1200,
    isNotified: false,
    projectPriority: 'medium',
    services: [],
    projectLogs: [],
    __v: 0
  },
  {
    projectName: 'logo redesign for a company',
    clientName: 'harsh sharma',
    bidAmount: null,
    desc: 'this is good',
    duration: '2025-10-26',
    userId: '105838001901535106407',
    userName: 'Bonhive',
    clientBudget: 12000,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'lead',
    IshourBillable: true,
    totalBill: 2.3333333333333335,
    totalHour: 0,
    totalMin: 0,
    totalSec: 7,
    hourlyRate: 1200,
    isNotified: false,
    projectPriority: 'medium',
    services: [[Object]],
    projectLogs: [[Object]],
    __v: 2
  },
  {
    projectName: 'logo redesign for a company',
    clientName: 'harsh sharma',
    bidAmount: null,
    desc: 'good for practice',
    duration: '2025-11-02',
    userId: '105838001901535106407',
    userName: 'Bonhive',
    clientBudget: 1000,
    email: 'harsh444577@gmail.com',
    contact: '9783333333',
    location: 'india',
    notes: 'this is good',
    leadSource: 'others',
    proposal: '',
    status: 'review',
    IshourBillable: true,
    totalBill: 1.3333333333333333,
    totalHour: 0,
    totalMin: 0,
    totalSec: 4,
    hourlyRate: 1200,
    isNotified: false,
    projectPriority: 'medium',
    services: [[Object], [Object]],
    projectLogs: [[Object]],
    __v: 3,
    completedMonth: 'Oct',
    tax_rate: '20'
  }

]



const ans = data.filter(fil => new Date(fil.duration) > new Date());


console.log(ans);
